export const CONTACT_LIST = 'Contacts'
export const HOME_NAVIGATOR = 'Home'
export const CREATE_CONTACT = 'Create Contact'
export const CONTACT_DETAILS = 'Contact details'
export const SETTINGS = 'Settings'
export const LOGIN = 'Login'
export const REGISTER = 'Register'
export const LOGOUT = 'Logout'
